//! Minimal shell-side integration.
//!
//! Phase 1's contract: when Termica spawns zsh, install a tiny
//! OSC 7 hook so the [`crate::osc::OscSniffer`] has something to
//! parse — without this, macOS zsh never emits OSC 7 (Apple's
//! `/etc/zshrc_Apple_Terminal` gates it on `$TERM_PROGRAM`).
//!
//! Mechanism is the classic [`ZDOTDIR`] override: we materialise a
//! Termica-owned directory containing `.zshenv`, `.zshrc`,
//! `.zlogin`, and `.zlogout` that each source the user's matching
//! file (so their personal config still runs) and then append our
//! snippet. Setting `ZDOTDIR=<our dir>` on the spawned shell makes
//! zsh read those files instead of the user's directly.
//!
//! [`ZDOTDIR`]: https://zsh.sourceforge.io/Doc/Release/Files.html
//!
//! Phase 3's full shell-integration installer will subsume this:
//! marker emission, deeper hooks, an opt-in installer subcommand,
//! cleanup. The scaffolding lives here so Phase 3 can extend it
//! rather than re-introduce the same mechanism.
//!
//! Opt out by setting `TERMICA_NO_SHELL_INTEGRATION=1` in the
//! environment; spawned shells then see the user's real
//! `$ZDOTDIR` (or none) untouched.

#![forbid(unsafe_code)]

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// The OSC 7 hook we append to the user's `.zshrc`. Embedded at
/// compile time so the binary is self-contained.
const ZSH_OSC7_SNIPPET: &str = include_str!("../integration/zsh-osc7.zsh");

/// Termica-owned data directory for shell-integration overrides.
///
/// Resolves to `$XDG_DATA_HOME/termica/` if set, else
/// `$HOME/Library/Application Support/Termica/` (macOS conventional),
/// else `$HOME/.local/share/termica/` (Linux fallback).
fn data_dir() -> Option<PathBuf> {
    if let Some(p) = std::env::var_os("XDG_DATA_HOME") {
        return Some(PathBuf::from(p).join("termica"));
    }
    let home = std::env::var_os("HOME")?;
    let home = PathBuf::from(home);
    if cfg!(target_os = "macos") {
        Some(home.join("Library/Application Support/Termica"))
    } else {
        Some(home.join(".local/share/termica"))
    }
}

/// Materialise a `ZDOTDIR` override directory and return its path.
///
/// The directory holds four files:
///
/// - `.zshenv` — sources the user's `$HOME/.zshenv` if it exists.
/// - `.zshrc`  — sources the user's `$HOME/.zshrc` if it exists,
///   then appends Termica's OSC 7 snippet.
/// - `.zlogin` / `.zlogout` — pass-through to the user's versions.
///
/// Returns `None` if `TERMICA_NO_SHELL_INTEGRATION=1` is set, if
/// `$HOME` is unset, or if any I/O step fails (we never break a
/// spawn over a failed integration write — the shell launches
/// without OSC 7 instead).
pub fn install_zsh_zdotdir() -> Option<PathBuf> {
    if std::env::var_os("TERMICA_NO_SHELL_INTEGRATION").is_some() {
        return None;
    }
    let home = std::env::var_os("HOME").map(PathBuf::from)?;
    let target = data_dir()?.join("zsh-integration");
    write_zdotdir_files(&home, &target).ok()?;
    Some(target)
}

/// Internal worker: writes the four override files into `target`,
/// sourcing the matching files in `home`. Idempotent — running
/// twice with the same inputs produces the same contents.
///
/// Public so unit tests can call it against a tmpdir without
/// touching the real `$HOME` or `$XDG_DATA_HOME`.
pub fn write_zdotdir_files(home: &Path, target: &Path) -> io::Result<()> {
    fs::create_dir_all(target)?;

    write_pass_through(home, target, ".zshenv", None)?;
    write_pass_through(home, target, ".zshrc", Some(ZSH_OSC7_SNIPPET))?;
    write_pass_through(home, target, ".zlogin", None)?;
    write_pass_through(home, target, ".zlogout", None)?;

    Ok(())
}

/// Write one pass-through file. If `append_snippet` is `Some`, the
/// snippet is appended after the user-source line.
fn write_pass_through(
    home: &Path,
    target: &Path,
    name: &str,
    append_snippet: Option<&str>,
) -> io::Result<()> {
    let user_path = home.join(name);
    let mut body = String::new();
    body.push_str("# Auto-generated by Termica's shell integration.\n");
    body.push_str("# Do not edit by hand; opt out with TERMICA_NO_SHELL_INTEGRATION=1.\n");
    body.push_str("# This file lives under Termica's data directory and is rewritten on every shell spawn.\n\n");
    body.push_str(&format!(
        "if [[ -f {q} ]]; then\n    source {q}\nfi\n",
        q = single_quote_zsh(&user_path.to_string_lossy())
    ));
    if let Some(snippet) = append_snippet {
        body.push('\n');
        body.push_str(snippet);
        if !snippet.ends_with('\n') {
            body.push('\n');
        }
    }
    fs::write(target.join(name), body)?;
    Ok(())
}

/// Quote a string for safe use inside a zsh single-quoted literal.
/// Single quote → close, backslash-quote, reopen.
fn single_quote_zsh(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

#[cfg(test)]
mod tests {
    //! Unit tests for the file-materialisation logic. The actual
    //! "zsh sees the hook" round-trip is covered by an integration
    //! test in `tests/zsh_integration.rs` that spawns a real zsh.

    use super::*;

    fn tmpdir() -> std::path::PathBuf {
        let mut p = std::env::temp_dir();
        // Per-test nonce: process id + monotonic counter via a small
        // atomic so concurrent tests don't collide.
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        p.push(format!("termica-test-integration-{}-{}", std::process::id(), n));
        let _ = fs::remove_dir_all(&p);
        fs::create_dir_all(&p).expect("create tmp dir");
        p
    }

    #[test]
    fn write_zdotdir_creates_all_four_files() {
        let root = tmpdir();
        let home = root.join("home");
        let target = root.join("zdot");
        fs::create_dir_all(&home).unwrap();

        write_zdotdir_files(&home, &target).expect("write");

        assert!(target.join(".zshenv").exists());
        assert!(target.join(".zshrc").exists());
        assert!(target.join(".zlogin").exists());
        assert!(target.join(".zlogout").exists());
    }

    #[test]
    fn zshrc_sources_user_file_and_includes_osc7_snippet() {
        let root = tmpdir();
        let home = root.join("home");
        let target = root.join("zdot");
        fs::create_dir_all(&home).unwrap();

        write_zdotdir_files(&home, &target).expect("write");

        let zshrc = fs::read_to_string(target.join(".zshrc")).expect("read .zshrc");
        // Sources the user's file (which may or may not exist; the
        // `[[ -f ... ]]` guard handles missing).
        let expected_source =
            format!("source {q}", q = single_quote_zsh(&home.join(".zshrc").to_string_lossy()));
        assert!(
            zshrc.contains(&expected_source),
            ".zshrc should source the user's file; got:\n{zshrc}"
        );
        // And contains a marker from our snippet — we won't pin the
        // whole snippet text but `__termica_emit_osc7` is uniquely ours.
        assert!(
            zshrc.contains("__termica_emit_osc7"),
            ".zshrc should embed the OSC 7 hook; got:\n{zshrc}"
        );
    }

    #[test]
    fn zshenv_sources_user_file_but_skips_osc7_snippet() {
        // OSC 7 belongs in .zshrc (interactive shells); .zshenv runs
        // for every zsh invocation including non-interactive scripts
        // and would spam them with escape sequences.
        let root = tmpdir();
        let home = root.join("home");
        let target = root.join("zdot");
        fs::create_dir_all(&home).unwrap();

        write_zdotdir_files(&home, &target).expect("write");

        let zshenv = fs::read_to_string(target.join(".zshenv")).expect("read .zshenv");
        assert!(zshenv.contains("source"));
        assert!(
            !zshenv.contains("__termica_emit_osc7"),
            ".zshenv must NOT contain the OSC 7 hook; got:\n{zshenv}"
        );
    }

    #[test]
    fn write_zdotdir_is_idempotent() {
        let root = tmpdir();
        let home = root.join("home");
        let target = root.join("zdot");
        fs::create_dir_all(&home).unwrap();

        write_zdotdir_files(&home, &target).expect("write 1");
        let first = fs::read_to_string(target.join(".zshrc")).expect("read 1");
        write_zdotdir_files(&home, &target).expect("write 2");
        let second = fs::read_to_string(target.join(".zshrc")).expect("read 2");
        assert_eq!(first, second, "two writes should produce identical content");
    }

    #[test]
    fn single_quote_zsh_handles_apostrophes() {
        // The classic problem: a path with a single quote in it.
        // Our quoting must produce a string that zsh re-reads as the
        // exact original.
        let q = single_quote_zsh("/Users/it's/code");
        assert_eq!(q, "'/Users/it'\\''s/code'");
    }
}
